model:
  default: gpt-3.5-turbo
  options:
    - gpt-3.5-turbo
    - gpt-4
enable_tools:
  default: false
recent_thoughts_count:
  default: 4
long_term_memory:
  default: false
ltm_recent_messages_count:
  default: 2
short_term_memory:
  default: true
enable_observations:
  default: true
humanize:
  default: true
temperature:
  default: 1.0
top_p:
  default: 1.0
max_tokens:
  default: 64
presence_penalty:
  default: 0.0
frequency_penalty:
  default: 0.0
